### PR TITLE
Remove <head> to fix build error

### PR DESCRIPTION
**Pull request by ashwindasr**

### CODE REVIEW

**Comment by ashwindasr** [comment]
Im merging this PR since it was breaking production heads up @MartinPl0

**Comment by MartinPl0** [comment]
Sure! Was the reason behind the build error the missing head import? I am bit confused as to why its missing as I though it was added here: https://github.com/openshift-eng/art-dashboard-ui/pull/70

**Comment by ashwindasr** [comment]
This line was causing issues with `npm next build`

**Comment by ashwindasr** [comment]
not the other issue that we were talking about

**Comment by MartinPl0** [comment]
Understand, thank you for explaining.

**Pull request merged**
